# Generated by Django 2.0.4 on 2018-07-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180628_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='标签名称')),
            ],
            options={
                'verbose_name_plural': '博客标签',
                'verbose_name': '博客标签',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_tags',
            field=models.ManyToManyField(related_name='blog_tags', to='blog.BlogTag', verbose_name='标签'),
        ),
    ]
