# Generated by Django 2.0.4 on 2018-07-08 07:14

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': '国家/地区',
                'verbose_name_plural': '国家/地区',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': '语言',
                'verbose_name_plural': '语言',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(default='', null=True, upload_to='poster', verbose_name='电影海报')),
                ('name', models.CharField(max_length=25, verbose_name='电影名字')),
                ('director', models.CharField(default='不详', max_length=25, verbose_name='导演')),
                ('scriptwriter', models.CharField(default='不详', max_length=50, verbose_name='编剧')),
                ('actor', models.CharField(default='', max_length=50, verbose_name='主演')),
                ('release_date', models.DateField(verbose_name='上映日期')),
                ('time_length', models.IntegerField(default=0, verbose_name='电影时长')),
                ('grade', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)], verbose_name='电影评分')),
                ('synopsis', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='剧情简介')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('resource', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='电影资源')),
                ('language', models.ManyToManyField(related_name='language', to='movies.Language', verbose_name='语言')),
            ],
            options={
                'ordering': ['-create_datetime'],
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
            },
        ),
        migrations.CreateModel(
            name='MovieLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines', models.TextField()),
                ('provenance', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '电影台词',
                'verbose_name_plural': '电影台词',
            },
        ),
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': '电影类型',
                'verbose_name_plural': '电影类型',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_type',
            field=models.ManyToManyField(related_name='movie_type', to='movies.MovieType', verbose_name='电影类型'),
        ),
        migrations.AddField(
            model_name='movie',
            name='producer_country',
            field=models.ManyToManyField(related_name='producer_country', to='movies.Country', verbose_name='制片国家'),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='release_country', to='movies.Country', verbose_name='上映国家'),
        ),
    ]
