# Generated by Django 2.0.4 on 2018-07-23 14:57

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVPlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(default='', null=True, upload_to='poster', verbose_name='海报')),
                ('name', models.CharField(max_length=25, verbose_name='名字')),
                ('director', models.CharField(default='不详', max_length=25, verbose_name='导演')),
                ('scriptwriter', models.CharField(default='不详', max_length=50, verbose_name='编剧')),
                ('actor', models.CharField(default='', max_length=50, verbose_name='主演')),
                ('release_date', models.DateField(verbose_name='上映日期')),
                ('season', models.IntegerField(default=0, verbose_name='第n季')),
                ('episode_num', models.IntegerField(default=0, verbose_name='集数')),
                ('time_length', models.IntegerField(default=0, verbose_name='片长')),
                ('grade', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)], verbose_name='评分')),
                ('synopsis', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='剧情简介')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('resource', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='资源')),
                ('language', models.ManyToManyField(related_name='tv_language', to='movies.Language', verbose_name='语言')),
                ('movie_type', models.ManyToManyField(related_name='tv_movie_type', to='movies.MovieType', verbose_name='类型')),
                ('producer_country', models.ManyToManyField(related_name='tv_producer_country', to='movies.Country', verbose_name='制片国家')),
                ('release_country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tv_release_country', to='movies.Country', verbose_name='上映国家')),
            ],
            options={
                'ordering': ['-create_datetime'],
                'verbose_name_plural': '电视剧',
                'verbose_name': '电视剧',
            },
        ),
    ]
