# Generated by Django 2.0.4 on 2018-08-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_tvplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_link',
            field=models.CharField(default='', max_length=250, verbose_name='预告片连接'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.CharField(default='', max_length=100, verbose_name='主演'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default='不详', max_length=50, verbose_name='导演'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='scriptwriter',
            field=models.CharField(default='不详', max_length=100, verbose_name='编剧'),
        ),
    ]
