# Generated by Django 2.0.4 on 2018-05-01 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
