# Generated by Django 2.0.4 on 2018-08-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20180822_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, default='', null=True, upload_to='poster', verbose_name='海报'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_link',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='预告片连接'),
        ),
    ]
