# Generated by Django 2.0.4 on 2018-05-01 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_create_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-create_datetime']},
        ),
    ]
