# Generated by Django 2.0.4 on 2018-05-04 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20180501_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines', models.CharField(max_length=255)),
                ('provenance', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='grade',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
