# Generated by Django 2.0.4 on 2018-05-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20180504_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielines',
            name='lines',
            field=models.TextField(),
        ),
    ]
