# Generated by Django 2.0.4 on 2018-05-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20180504_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='', null=True, upload_to='poster', verbose_name='电影海报'),
        ),
    ]
