# Generated by Django 2.0.4 on 2018-05-06 02:49

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20180506_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.CharField(default='', max_length=25, verbose_name='主演'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=25, verbose_name='导演'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='grade',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)], verbose_name='电影评分'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.Language', verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.MovieType', verbose_name='电影类型'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=25, verbose_name='电影名字'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='producer_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.Country', verbose_name='制片国家'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_country',
            field=models.CharField(max_length=20, verbose_name='上映国家'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(verbose_name='上映日期'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='剧情简介'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='time_length',
            field=models.IntegerField(default=0, verbose_name='电影时长'),
        ),
    ]
