# Generated by Django 2.0.4 on 2018-05-06 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20180506_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='producer_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='producer_country', to='movies.Country', verbose_name='制片国家'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='release_country', to='movies.Country', verbose_name='上映国家'),
        ),
    ]
