# Generated by Django 2.0.4 on 2018-06-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20180506_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_type',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_type',
            field=models.ManyToManyField(to='movies.MovieType', verbose_name='电影类型'),
        ),
    ]
