# Generated by Django 2.0.4 on 2018-06-12 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20180612_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_type',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='movies.MovieType', verbose_name='电影类型'),
            preserve_default=False,
        ),
    ]
