# Generated by Django 2.0.4 on 2018-06-15 14:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20180612_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='resource',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='电影资源'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.CharField(default='', max_length=50, verbose_name='主演'),
        ),
    ]
