# Generated by Django 2.0.4 on 2018-06-20 08:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20180615_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='producer_country',
        ),
        migrations.AddField(
            model_name='movie',
            name='producer_country',
            field=models.ManyToManyField(related_name='producer_country', to='movies.Country', verbose_name='制片国家'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='resource',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='电影资源'),
        ),
    ]
