# Generated by Django 2.0.4 on 2018-06-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20180620_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.ManyToManyField(related_name='language', to='movies.Language', verbose_name='语言'),
        ),
    ]
