# Generated by Django 2.0.4 on 2018-06-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20180620_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='scriptwriter',
            field=models.CharField(default='不详', max_length=50, verbose_name='编剧'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default='不详', max_length=25, verbose_name='导演'),
        ),
    ]
