# Generated by Django 2.0.4 on 2018-06-27 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20180620_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '国家/地区', 'verbose_name_plural': '国家/地区'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': '语言', 'verbose_name_plural': '语言'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-create_datetime'], 'verbose_name': '电影', 'verbose_name_plural': '电影'},
        ),
        migrations.AlterModelOptions(
            name='movielines',
            options={'verbose_name': '电影台词', 'verbose_name_plural': '电影台词'},
        ),
        migrations.AlterModelOptions(
            name='movietype',
            options={'verbose_name': '电影类型', 'verbose_name_plural': '电影类型'},
        ),
    ]
